language: node_js

node_js:
  - "node"

services:
  - postgresql

script: npm test

addons:
  postgresql: "9.4"

before_script:
  - npm install
  - psql -c 'create database doc-api;' -U postgres
  - npm run seed

after_success:
  - npm run coveralls