language: node_js
node_js:
  - "node"
services:
  - postgresql
script: npm test
before_script:
  - npm install
  - psql -c 'create database travis;' -U postgres
  - npm run seed
after_success:
  - npm run coveralls